/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Control: typeof import("./../src/components/FlowChart/components/Control.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    FlowChart: typeof import("./../src/components/FlowChart/index.vue")["default"];
    GraphDataDialog: typeof import("./../src/components/FlowChart/components/GraphDataDialog.vue")["default"];
    Grid: typeof import("./../src/components/Grid/index.vue")["default"];
    GridItem: typeof import("./../src/components/Grid/components/GridItem.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchForm: typeof import("./../src/components/SearchForm/index.vue")["default"];
    SearchFormItem: typeof import("./../src/components/SearchForm/components/SearchFormItem.vue")["default"];
    SvgIcon: typeof import("./../src/components/SvgIcon/index.vue")["default"];
    TableColumn: typeof import("./../src/components/TableView/components/TableColumn.vue")["default"];
    TableFooter: typeof import("./../src/components/TableView/components/TableFooter.vue")["default"];
    TableHeader: typeof import("./../src/components/TableView/components/TableHeader.vue")["default"];
    TableView: typeof import("./../src/components/TableView/index.vue")["default"];
    UploadImg: typeof import("./../src/components/Upload/UploadImg.vue")["default"];
    UploadImgs: typeof import("./../src/components/Upload/UploadImgs.vue")["default"];
    WangEditor: typeof import("./../src/components/WangEditor/index.vue")["default"];
  }
}
